# Metal Spotlight Long-Conversation Constraint Retention With Talk2AI

This notebook uses the Apple Silicon `HookLLMMetal` Spotlight path to run a long-turn conversation experiment seeded from the Talk2AI dataset used in `tools/talk2ai_vllm_metal_long_conversation.ipynb`.

It compares ordinary generation against Spotlight-steered generation while a persistent constraint block is emphasized in the prompt and the Talk2AI conversation context grows. Each assistant reply is checked for state-of-being verb violations with a spaCy POS tagger.

### Setup

Run this notebook from the `vllm-metal` environment described in `notebooks/metal/README.md`. It assumes this repo is installed or importable in that environment.

In [1]:
from pathlib import Path
import sys

repo_root = Path.cwd()
if repo_root.name == "metal":
    repo_root = repo_root.parents[1]
elif repo_root.name == "notebooks":
    repo_root = repo_root.parent

plugin_src = repo_root / "vllm_hook_plugins"
if str(plugin_src) not in sys.path:
    sys.path.insert(0, str(plugin_src))

print(f"Repo root: {repo_root}")
print(f"Plugin source: {plugin_src}")

Repo root: /Users/timothyburley/opensource/vLLM-Hook
Plugin source: /Users/timothyburley/opensource/vLLM-Hook/vllm_hook_plugins

### Imports And Metal Environment

In [2]:
import json
import os
import time
import urllib.request
from datetime import datetime
from pathlib import Path

import pandas as pd
import torch
from vllm import SamplingParams
from vllm_hook_plugins.metal import HookLLMMetal
from vllm_hook_plugins.utils.spotlight.utils import get_span_ranges
from transformers import AutoTokenizer

os.environ["VLLM_USE_V1"] = "1"
os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"
os.environ.setdefault("VLLM_ENABLE_V1_MULTIPROCESSING", "0")
os.environ.setdefault("VLLM_METAL_USE_PAGED_ATTENTION", "0")
os.environ.setdefault("VLLM_METAL_MEMORY_FRACTION", "auto")

print("Metal Spotlight long-conversation environment configured")

INFO 09-10 07:22:40 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 09-10 07:22:40 [__init__.py:46] - metal -> vllm_metal:register
INFO 09-10 07:22:40 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 09-10 07:22:44 [__init__.py:238] Platform plugin metal is activated
INFO 09-10 07:22:45 [importing.py:69] Triton not installed or not compatible; certain GPU-related functions will not be available.
Metal Spotlight long-conversation environment configured

### Load The Metal Spotlight Model

The default model is intentionally small for Apple Silicon iteration. Increase `max_model_len` and switch models after confirming the experiment works on your machine.

In [3]:
cache_dir = str(repo_root / "cache")
model = "Qwen/Qwen2-1.5B-Instruct"
MAX_MODEL_LEN = 32000


def build_metal_spotlight_llm():
    return HookLLMMetal(
        model=model,
        worker_name="probe_spotlight",
        download_dir=cache_dir,
        trust_remote_code=True,
        dtype=torch.float16,
        enable_hook=True,
        gpu_memory_utilization=0.30,
        max_model_len=MAX_MODEL_LEN,
        max_num_seqs=1,
        enforce_eager=True,
        enable_prefix_caching=False,
        enable_chunked_prefill=False,
    )


llm = build_metal_spotlight_llm()

SPOTLIGHT_TOKENIZER = AutoTokenizer.from_pretrained(
    model,
    cache_dir=cache_dir,
    trust_remote_code=True,
)
if SPOTLIGHT_TOKENIZER.pad_token is None:
    SPOTLIGHT_TOKENIZER.pad_token = SPOTLIGHT_TOKENIZER.eos_token

print(f"Model loaded: {model}")
print("Metal Spotlight worker enabled")
print("Spotlight span tokenizer ready")
print(f"Max model length: {MAX_MODEL_LEN}")

HookLLMMetal worker=probe_spotlight hooks_enabled=True
INFO 09-10 07:22:46 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:22:46 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:22:46 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:22:46 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:22:47 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:22:47 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:22:47 [model.py:1752] Using max model len 32000
WARNING 09-10 07:22:47 [arg_utils.py:2383] This model does not officially support disabling chunked prefill. Disabling this manually may cause the engine to crash or produce incorrect outputs.
INFO 09-10 07:22:47 [vllm.py:977] Asynchronous scheduling is enabled.
WARNING 09-10 07:22:47 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:22:47 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:22:47 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:22:47 [platform.py:324] Metal memory: 34.4GB total, 20.0GB available
INFO 09-10 07:22:47 [compilation.py:312] Enabled custom fusions: norm_quant, act_quant
INFO 09-10 07:22:49 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:22:49 [worker_base.py:282] Injected <class 'vllm_hook_plugins.workers.metal.spotlight_worker_metal.SpotlightWorkerMetal'> into <class 'vllm_metal.v1.worker.MetalWorker'> for extended collective_rpc calls ['_causal_mask', '_compute_spotlight_output', '_ensure_extension_state', '_has_attention_api', '_inner_module', '_install_hooks', '_match_attn', '_repeat_kv', '_request_spotlight_params', '_spotlight_hook', '_stage', '_uninstall_hooks', 'install_hooks']
INFO 09-10 07:22:49 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:22:49 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:22:49 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:22:49 [parallel_state.py:1422] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:50692 backend=gloo
INFO 09-10 07:22:49 [parallel_state.py:1735] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-10 07:22:49 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)

mx.metal.device_info is deprecated and will be removed in a future version. Use mx.device_info instead.

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 7 files:   0%|          | 0/7 [00:00<?, ?it/s]

INFO 09-10 07:22:51 [model_lifecycle.py:187] Model loaded in 1.34s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:22:51 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:22:51 [kv_cache_utils.py:1733] GPU KV cache size: 32,000 tokens
INFO 09-10 07:22:51 [kv_cache_utils.py:1734] Maximum concurrency for 32,000 tokens per request: 1.00x
INFO 09-10 07:22:51 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:22:51 [model_runner.py:649] Warming up model...
INFO 09-10 07:22:51 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:22:51 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.09 s (compilation: 0.09 s)
Model loaded: Qwen/Qwen2-1.5B-Instruct
Metal Spotlight worker enabled
Spotlight span tokenizer ready
Max model length: 32000

### Load Talk2AI Conversations

Point `TALK2AI_LOCAL_PATH` at the real Talk2AI JSON when you have it. The loader matches the original long-conversation notebook: it tries a local file, then the paper-indicated GitHub URL, then falls back to a small synthetic sample with the same shape so the notebook remains runnable.

In [4]:
# If you already have a copy of talk2ai_conversations.json, point this at it.
TALK2AI_LOCAL_PATH = None  # e.g. "/Users/you/Downloads/talk2ai_conversations.json"

TALK2AI_CANDIDATE_URLS = [
    "https://raw.githubusercontent.com/MassimoStel/Talk2AI/main/Data_paper/talk2ai_conversations.json",
]


def _download_json(url, timeout=15):
    req = urllib.request.Request(url, headers={"User-Agent": "vllm-hook-talk2ai-notebook/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def build_synthetic_talk2ai_sample():
    return [
        {
            "conversationId": "synthetic-climate-001",
            "topic": "climate change",
            "messages": [
                {"role": "user", "content": "Honestly, I think how much climate change gets talked about is overblown compared to other problems we have."},
                {"role": "assistant", "content": "That's a common view, so let's look at it together. What makes it feel overblown to you - the media coverage, the urgency of the language, or something else?"},
                {"role": "user", "content": "Mostly the media coverage. It feels like every week there's a new 'worst ever' headline."},
                {"role": "assistant", "content": "That pattern is real, and it can create headline fatigue even when the underlying trend is genuinely worsening. Would it help to look at a couple of long-run measurements instead of headlines?"},
            ],
        },
        {
            "conversationId": "synthetic-mathanxiety-001",
            "topic": "math anxiety",
            "messages": [
                {"role": "user", "content": "I freeze up during math tests even when I know the material. It's embarrassing."},
                {"role": "assistant", "content": "That's a really common experience and it has a name - math anxiety - and it's not about ability. Does the freezing happen mostly during timed tests, or also with untimed homework?"},
                {"role": "user", "content": "Mostly timed tests. My mind just goes blank."},
                {"role": "assistant", "content": "Time pressure is one of the biggest triggers for that blanking response. A few students find it helps to do a short breathing reset before the clock starts - want to walk through one?"},
            ],
        },
        {
            "conversationId": "synthetic-healthmisinfo-001",
            "topic": "health misinformation",
            "messages": [
                {"role": "user", "content": "A friend sent me a post saying a common vaccine ingredient causes serious harm. Is that true?"},
                {"role": "assistant", "content": "That specific claim has been examined closely and hasn't held up under review. Do you want me to walk through what the ingredient actually does and where that claim seems to have come from?"},
                {"role": "user", "content": "Yeah, I'd like to understand where it came from."},
                {"role": "assistant", "content": "Sure - a lot of claims like this trace back to a single misinterpreted or retracted study that keeps getting recirculated. Let's look at the original source."},
            ],
        },
    ]


def load_talk2ai(local_path=TALK2AI_LOCAL_PATH, candidate_urls=TALK2AI_CANDIDATE_URLS):
    if local_path and os.path.exists(local_path):
        print(f"Loading Talk2AI conversations from local file: {local_path}")
        with open(local_path) as f:
            return json.load(f), "local_file"

    for url in candidate_urls:
        try:
            print(f"Attempting to download Talk2AI conversations from {url} ...")
            data = _download_json(url)
            print("Download succeeded.")
            return data, "remote_download"
        except Exception as exc:
            print(f"  could not fetch from {url}: {exc}")

    print("Could not locate the real Talk2AI dataset. Falling back to the synthetic Talk2AI-shaped sample.")
    return build_synthetic_talk2ai_sample(), "synthetic_fallback"


conversations, dataset_source = load_talk2ai()
print(f"Loaded {len(conversations)} conversation(s) - source: {dataset_source}")

Attempting to download Talk2AI conversations from https://raw.githubusercontent.com/MassimoStel/Talk2AI/main/Data_paper/talk2ai_conversations.json ...
  could not fetch from https://raw.githubusercontent.com/MassimoStel/Talk2AI/main/Data_paper/talk2ai_conversations.json: HTTP Error 404: Not Found
Could not locate the real Talk2AI dataset. Falling back to the synthetic Talk2AI-shaped sample.
Loaded 3 conversation(s) - source: synthetic_fallback

### Select A Talk2AI Seed Conversation

The experiment replays user turns from this Talk2AI seed and inserts newly generated assistant turns for each condition. Change `SEED_INDEX` or filter by `topic` to try a different conversation.

In [5]:
SEED_INDEX = 0
seed = conversations[SEED_INDEX]
seed_messages = [m for m in seed.get("messages", []) if m.get("role") in {"user", "assistant"}]
USER_TURNS = [m["content"] for m in seed_messages if m.get("role") == "user"]

if not USER_TURNS:
    raise ValueError("Selected Talk2AI conversation has no user turns to replay.")

print("conversationId:", seed.get("conversationId"))
print("topic         :", seed.get("topic"))
print("dataset_source:", dataset_source)
print("seed user turns:", len(USER_TURNS))
print()
for m in seed_messages[:8]:
    print(f"[{m['role']}] {m['content']}")

conversationId: synthetic-climate-001
topic         : climate change
dataset_source: synthetic_fallback
seed user turns: 2

[user] Honestly, I think how much climate change gets talked about is overblown compared to other problems we have.
[assistant] That's a common view, so let's look at it together. What makes it feel overblown to you - the media coverage, the urgency of the language, or something else?
[user] Mostly the media coverage. It feels like every week there's a new 'worst ever' headline.
[assistant] That pattern is real, and it can create headline fatigue even when the underlying trend is genuinely worsening. Would it help to look at a couple of long-run measurements instead of headlines?

### Experiment Configuration

Each turn asks the model to answer a fresh user message while preserving the same constraints. Spotlight emphasizes the constraint block in the full prompt.

In [6]:
CONSTRAINT_BLOCK = """Persistent constraints:
1. Do not use state of being verbs [am, is, are, was, were, be, being, been], 
or contractions containing state of being verbs.
""".strip()


SYSTEM_MESSAGE = (
    "You are a concise assistant continuing a Talk2AI-style conversation about "
    f"{seed.get('topic', 'the selected topic')}. Preserve nuance, acknowledge uncertainty, "
    "and adapt as the participant's concerns evolve."
)
ALPHA = 0.2
SAMPLING_PARAMS = SamplingParams(temperature=0.0, max_tokens=96)
TARGET_USER_TURNS = 50
HISTORY_WINDOW_MESSAGES = 12  # six recent user/assistant exchanges kept in each prompt

CONVERSATION_ARCS = {
    "climate change": [
        "I get that headlines can exaggerate, but I still wonder whether the long-term measurements are being framed fairly.",
        "If the temperature trend is real, why do people in my town still argue from whatever the weather was like this winter?",
        "I am not denying the data, but I worry that every proposed fix seems expensive for ordinary households.",
        "What is the strongest argument that current climate policy asks too much too quickly?",
        "How should I think about countries that industrialized earlier asking poorer countries to slow down now?",
        "A friend says adaptation is more realistic than prevention. Where is that view right, and where does it break down?",
        "Can you separate personal choices, local policy, and national policy without making one sound like the whole answer?",
        "I hear people say the models have been wrong before. What kind of uncertainty actually matters here?",
        "If someone works in oil, gas, shipping, or farming, what would a fair transition even mean?",
        "I am bothered by activists who sound certain about everything. Does that hurt the credibility of the underlying science?",
        "What would be a practical climate action that is boring but actually high leverage?",
        "How do we avoid climate concern turning into a status signal instead of useful behavior?",
        "If electricity demand is growing because of AI and data centers, does that change the clean energy argument?",
        "What is a realistic timeline for change that is urgent but not fantasy?",
        "Can you explain how risk compounds without making it sound like immediate doom?",
        "Where do carbon offsets fit in, if at all? I hear both praise and accusations of greenwashing.",
        "What would you say to someone who thinks climate policy is mostly political control?",
        "How do insurance prices, food prices, and infrastructure costs make this issue less abstract?",
        "I want to talk about tradeoffs honestly. What gets worse if we move too slowly, and what gets worse if we move too fast?",
        "What is the best local question to ask a city council candidate about this?",
        "Suppose I only changed one habit this year. Which change would be meaningful without pretending I solved the problem?",
        "How do I tell the difference between serious criticism of a policy and misinformation about the science?",
        "What is one thing climate communicators should stop doing?",
        "What is one thing skeptics should concede if they are arguing in good faith?",
        "Can you end this part by giving me a position that is cautious, practical, and still evidence-based?",
    ],
    "math anxiety": [
        "I know practice matters, but timed tests make me feel like my brain is shutting down before I start.",
        "How can I tell the difference between not understanding the material and panicking while I do understand it?",
        "I hate advice that sounds like just relax. What is a concrete first step during the first minute of a test?",
        "What should a teacher change that would help anxious students without lowering standards?",
        "If I use accommodations, I worry people will think I am getting an unfair advantage. How should I think about that?",
        "Can you explain why smart people can still freeze on basic problems?",
        "What is a good way to review mistakes without turning it into proof that I am bad at math?",
        "How should parents talk about grades when anxiety is part of the problem?",
        "What is the role of memorization versus conceptual understanding here?",
        "Can you give an example of a study routine that builds confidence gradually?",
        "What if the anxiety comes from one bad teacher or one humiliating class experience?",
        "How do I ask for help without sounding like I am making excuses?",
        "What would progress look like over a month, not overnight?",
        "Are there cases where pushing through is helpful and cases where it backfires?",
        "How should I handle a blank mind when everyone else seems to be working?",
        "What can a school do to avoid making math identity feel fixed?",
        "Can you compare test anxiety in math with stage fright or sports pressure?",
        "What should I do after a bad score so I do not spiral?",
        "How do I keep ambition without tying my self-worth to performance?",
        "What is a fair way to measure improvement when the grade is still uneven?",
        "Can you end this part with a plan that is compassionate but not vague?",
    ],
    "health misinformation": [
        "I do not want to overreact to a viral post, but I also do not want to dismiss a real safety concern.",
        "How can I check a health claim without needing a medical degree?",
        "What makes a source trustworthy besides having a professional-looking website?",
        "If someone had a bad experience after a treatment, how do we respect that without assuming causation?",
        "Why do ingredient names sound scary even when the dose or context matters?",
        "What should I say to a friend who thinks fact-checking sites are biased?",
        "Can you explain absolute risk versus relative risk with a health example?",
        "What is the strongest fair criticism of public health messaging in recent years?",
        "How do I talk to family without making them defensive?",
        "What warning signs suggest a post is selling fear rather than information?",
        "If official guidance changes, how do I know whether that is learning or incompetence?",
        "What does consensus mean if individual doctors sometimes disagree?",
        "How should I think about rare side effects without exaggerating or ignoring them?",
        "What is a practical checklist before sharing a health claim?",
        "How do influencers exploit uncertainty in medical topics?",
        "What would make you pause and investigate a claim further?",
        "Can you explain why anecdotes feel more persuasive than population data?",
        "What is one respectful question I can ask someone who believes a dubious claim?",
        "How do platforms reward the most alarming version of a health story?",
        "Can you end this part with a cautious, humane approach to evaluating claims?",
    ],
}

GENERAL_ARC = [
    "I see your point, but I still feel conflicted because the issue affects different groups unevenly.",
    "Can you separate what is strongly supported from what is still uncertain? I do not want a one-sided answer.",
    "What would someone skeptical of your last point say, and which part of that criticism is fair?",
    "Bring this back to everyday decisions. What would change for a person who only has limited time and money?",
    "Where do values enter the discussion, not just facts?",
    "What evidence would actually change your mind about this?",
    "Can you distinguish between a good-faith concern and a misleading talking point?",
    "What should I watch for over the next few years to update my view?",
]

PHASE_BRIDGES = [
    "Let me push on that from a practical angle.",
    "I want to make this less abstract.",
    "Here is the part I still find hard to reconcile.",
    "Suppose I am talking to someone who disagrees with me.",
    "I am trying to update my view without just adopting a slogan.",
    "Before moving on, I want to test the tradeoff.",
]


def topic_arc(topic):
    normalized = (topic or "").lower()
    for key, turns in CONVERSATION_ARCS.items():
        if key in normalized:
            return turns
    return GENERAL_ARC


def build_long_user_turns(seed_turns, topic, target_turns):
    turns = [turn.strip() for turn in seed_turns if turn and turn.strip()]
    if not turns:
        turns = [f"I want to talk through {topic}, but I am not sure what to believe yet."]

    arc = topic_arc(topic)
    index = 0
    while len(turns) < target_turns:
        bridge = PHASE_BRIDGES[index % len(PHASE_BRIDGES)]
        angle = arc[index % len(arc)]
        if index >= len(arc):
            angle = f"Returning to this from another angle: {angle}"
        turns.append(f"{bridge} {angle}")
        index += 1
    return turns[:target_turns]


TALK2AI_USER_TURNS = list(USER_TURNS)
USER_TURNS = build_long_user_turns(
    TALK2AI_USER_TURNS,
    seed.get("topic", "the selected Talk2AI topic"),
    TARGET_USER_TURNS,
)
MAX_USER_TURNS = len(USER_TURNS)

print(CONSTRAINT_BLOCK)
print(f"Seed Talk2AI user turns: {len(TALK2AI_USER_TURNS)}")
print(f"Expanded user turns: {MAX_USER_TURNS}")
print(f"Prompt history window messages: {HISTORY_WINDOW_MESSAGES}")
print("Preview of final generated user turn:")
print(USER_TURNS[-1])

Persistent constraints:
1. Do not use state of being verbs [am, is, are, was, were, be, being, been],
or contractions containing state of being verbs.
Seed Talk2AI user turns: 2
Expanded user turns: 50
Prompt history window messages: 12
Preview of final generated user turn:
Before moving on, I want to test the tradeoff. Returning to this from another angle: What is one thing climate communicators should stop doing?

### Prompt And Scoring Helpers

In [7]:
def render_prompt(history, user_message):
    recent_history = history[-HISTORY_WINDOW_MESSAGES:]
    omitted_messages = max(0, len(history) - len(recent_history))
    transcript = "\n".join(
        f"{item['role'].upper()}: {item['content']}" for item in recent_history
    )
    if transcript:
        transcript = transcript + "\n"

    earlier_context = ""
    if omitted_messages:
        earlier_context = (
            f"Earlier conversation context: {omitted_messages} older messages are omitted "
            f"from this prompt to keep the Metal run within memory limits. Continue the same "
            f"Talk2AI conversation about {seed.get('topic')}.\n\n"
        )

    return f"""{SYSTEM_MESSAGE}

Talk2AI conversation id: {seed.get('conversationId')}
Topic: {seed.get('topic')}

{CONSTRAINT_BLOCK}

{earlier_context}Recent conversation:
{transcript}USER: {user_message}
ASSISTANT:""".strip()


def clean_text(text):
    return text.strip().split("\n\n")[0].strip()


def build_spotlight_sampling_params(prompt, base_params, emph_string, alpha):
    tokenized = SPOTLIGHT_TOKENIZER(
        [prompt],
        return_tensors="pt",
        return_offsets_mapping=True,
        padding=True,
    )
    offset_mappings = tokenized.pop("offset_mapping")
    span_ranges = get_span_ranges([prompt], [[emph_string]], offset_mappings)

    import copy

    params = copy.copy(base_params)
    extra = dict(params.extra_args or {})
    extra["spotlight"] = {
        "span_ranges": span_ranges[0],
        "alpha": alpha,
    }
    params.extra_args = extra
    return params

### Run Baseline And Spotlight Conditions

In [8]:
def run_condition(name, use_spotlight, model_runner):
    history = []
    rows = []
    for turn_index, user_message in enumerate(USER_TURNS[:MAX_USER_TURNS], start=1):
        prompt = render_prompt(history, user_message)
        start = time.perf_counter()
        if use_spotlight:
            spotlight_params = build_spotlight_sampling_params(
                prompt,
                SAMPLING_PARAMS,
                CONSTRAINT_BLOCK,
                ALPHA,
            )
            outputs = model_runner.generate(
                prompts=[prompt],
                sampling_params=spotlight_params,
                use_hook=True,
            )
        else:
            outputs = model_runner.generate(
                prompts=[prompt],
                sampling_params=SAMPLING_PARAMS,
                use_hook=False,
            )
        elapsed_s = time.perf_counter() - start
        reply = clean_text(outputs[0].outputs[0].text)
        rows.append(
            {
                "condition": name,
                "turn": turn_index,
                "conversation_id": seed.get("conversationId"),
                "topic": seed.get("topic"),
                "dataset_source": dataset_source,
                "user_message": user_message,
                "prompt_chars": len(prompt),
                "history_messages_in_prompt": min(len(history), HISTORY_WINDOW_MESSAGES),
                "latency_s": elapsed_s,
                "reply": reply,
            }
        )
        history.extend(
            [
                {"role": "user", "content": user_message},
                {"role": "assistant", "content": reply},
            ]
        )
        print(f"{name} turn {turn_index}: latency={elapsed_s:.2f}s")
    return rows


baseline_rows = run_condition("baseline", use_spotlight=False, model_runner=llm)

# Free the baseline engine before the Spotlight condition. HookLLMMetal's Spotlight
# path builds a hook-enabled engine per call, and the memory guard checks available
# host memory before that setup starts.
llm.shutdown()
del llm
import gc
gc.collect()

llm = build_metal_spotlight_llm()
spotlight_rows = run_condition("spotlight", use_spotlight=True, model_runner=llm)
results = pd.DataFrame(baseline_rows + spotlight_rows)
results

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it, est. speed input: 34.27 toks/s, output: 27.19 toks/s]

baseline turn 1: latency=3.56s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it, est. speed input: 65.33 toks/s, output: 28.00 toks/s]

baseline turn 2: latency=3.44s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.57s/it, est. speed input: 100.65 toks/s, output: 26.91 toks/s]

baseline turn 3: latency=3.58s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it, est. speed input: 145.86 toks/s, output: 28.35 toks/s]

baseline turn 4: latency=3.40s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.65s/it, est. speed input: 171.97 toks/s, output: 26.29 toks/s]

baseline turn 5: latency=3.66s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it, est. speed input: 215.29 toks/s, output: 27.30 toks/s]

baseline turn 6: latency=3.53s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.64s/it, est. speed input: 244.86 toks/s, output: 26.38 toks/s]

baseline turn 7: latency=3.66s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.65s/it, est. speed input: 262.37 toks/s, output: 26.29 toks/s]

baseline turn 8: latency=3.67s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.55s/it, est. speed input: 272.88 toks/s, output: 27.06 toks/s]

baseline turn 9: latency=3.64s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.59s/it, est. speed input: 268.62 toks/s, output: 26.78 toks/s]

baseline turn 10: latency=3.60s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.55s/it, est. speed input: 270.85 toks/s, output: 27.03 toks/s]

baseline turn 11: latency=3.59s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.57s/it, est. speed input: 270.15 toks/s, output: 26.90 toks/s]

baseline turn 12: latency=3.58s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.61s/it, est. speed input: 268.01 toks/s, output: 26.63 toks/s]

baseline turn 13: latency=3.62s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.60s/it, est. speed input: 267.39 toks/s, output: 26.66 toks/s]

baseline turn 14: latency=3.61s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it, est. speed input: 272.04 toks/s, output: 27.26 toks/s]

baseline turn 15: latency=3.54s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.69s/it, est. speed input: 257.15 toks/s, output: 26.01 toks/s]

baseline turn 16: latency=3.70s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.80s/it, est. speed input: 249.35 toks/s, output: 25.25 toks/s]

baseline turn 17: latency=3.83s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.65s/it, est. speed input: 259.67 toks/s, output: 26.30 toks/s]

baseline turn 18: latency=3.67s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.67s/it, est. speed input: 257.24 toks/s, output: 26.16 toks/s]

baseline turn 19: latency=3.68s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it, est. speed input: 265.46 toks/s, output: 26.97 toks/s]

baseline turn 20: latency=3.58s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.54s/it, est. speed input: 270.28 toks/s, output: 27.17 toks/s]

baseline turn 21: latency=3.55s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.70s/it, est. speed input: 256.06 toks/s, output: 25.93 toks/s]

baseline turn 22: latency=3.72s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it, est. speed input: 264.51 toks/s, output: 26.51 toks/s]

baseline turn 23: latency=3.63s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it, est. speed input: 266.08 toks/s, output: 26.55 toks/s]

baseline turn 24: latency=3.63s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.64s/it, est. speed input: 262.42 toks/s, output: 26.41 toks/s]

baseline turn 25: latency=3.65s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.67s/it, est. speed input: 260.17 toks/s, output: 26.18 toks/s]

baseline turn 26: latency=3.68s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.69s/it, est. speed input: 258.83 toks/s, output: 25.99 toks/s]

baseline turn 27: latency=3.71s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it, est. speed input: 268.40 toks/s, output: 26.98 toks/s]

baseline turn 28: latency=3.57s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.83s/it, est. speed input: 254.71 toks/s, output: 25.10 toks/s]

baseline turn 29: latency=3.84s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.70s/it, est. speed input: 264.73 toks/s, output: 25.93 toks/s]

baseline turn 30: latency=3.72s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.69s/it, est. speed input: 267.19 toks/s, output: 26.01 toks/s]

baseline turn 31: latency=3.71s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it, est. speed input: 276.13 toks/s, output: 26.53 toks/s]

baseline turn 32: latency=3.63s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.74s/it, est. speed input: 270.25 toks/s, output: 25.66 toks/s]

baseline turn 33: latency=3.76s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.16s/it, est. speed input: 244.57 toks/s, output: 23.11 toks/s]

baseline turn 34: latency=4.18s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it, est. speed input: 316.78 toks/s, output: 29.93 toks/s]

baseline turn 35: latency=3.24s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it, est. speed input: 305.42 toks/s, output: 28.94 toks/s]

baseline turn 36: latency=3.33s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.13s/it, est. speed input: 246.56 toks/s, output: 23.30 toks/s]

baseline turn 37: latency=4.15s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.02s/it, est. speed input: 252.53 toks/s, output: 23.88 toks/s]

baseline turn 38: latency=4.07s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.69s/it, est. speed input: 274.38 toks/s, output: 26.05 toks/s]

baseline turn 39: latency=3.72s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  4.00s/it, est. speed input: 251.82 toks/s, output: 24.03 toks/s]

baseline turn 40: latency=4.01s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.79s/it, est. speed input: 264.65 toks/s, output: 25.36 toks/s]

baseline turn 41: latency=3.80s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.79s/it, est. speed input: 263.57 toks/s, output: 25.38 toks/s]

baseline turn 42: latency=3.80s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.74s/it, est. speed input: 267.07 toks/s, output: 25.66 toks/s]

baseline turn 43: latency=3.77s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.75s/it, est. speed input: 264.33 toks/s, output: 25.58 toks/s]

baseline turn 44: latency=3.77s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.65s/it, est. speed input: 271.94 toks/s, output: 26.32 toks/s]

baseline turn 45: latency=3.67s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.77s/it, est. speed input: 266.16 toks/s, output: 25.50 toks/s]

baseline turn 46: latency=3.78s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it, est. speed input: 241.85 toks/s, output: 23.22 toks/s]

baseline turn 47: latency=4.16s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.89s/it, est. speed input: 259.24 toks/s, output: 24.71 toks/s]

baseline turn 48: latency=4.04s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.73s/it, est. speed input: 271.86 toks/s, output: 25.76 toks/s]

baseline turn 49: latency=3.75s

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.87s/it, est. speed input: 258.79 toks/s, output: 24.79 toks/s]

baseline turn 50: latency=3.89s
HookLLMMetal worker=probe_spotlight hooks_enabled=True
INFO 09-10 07:25:57 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}

WARNING 09-10 07:25:57 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:25:57 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:25:58 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:25:58 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:25:58 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:25:58 [model.py:1752] Using max model len 32000
WARNING 09-10 07:25:58 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:25:58 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:25:58 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:25:58 [platform.py:324] Metal memory: 34.4GB total, 21.3GB available
INFO 09-10 07:25:59 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:25:59 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:25:59 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:25:59 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:00 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:00 [model_lifecycle.py:151] Model loaded from cache in 0.002s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:00 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:00 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:00 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:00 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:00 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.11 s (compilation: 0.11 s)
Metal steer: preparing hook run
Metal steer: host before hook setup rss=3.40 GB available=19.49 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=3.40 GB available=19.50 GB total=32.00 GB
INFO 09-10 07:26:00 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:00 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:00 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:00 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:26:00 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:00 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:00 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:00 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:00 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:00 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:00 [platform.py:324] Metal memory: 34.4GB total, 20.9GB available
INFO 09-10 07:26:01 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:01 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:01 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:01 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:02 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:02 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:02 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:02 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:02 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:02 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:02 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.57s/it, est. speed input: 33.88 toks/s, output: 26.88 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=3.58 GB available=18.77 GB total=32.00 GB
spotlight turn 1: latency=5.57s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=3.58 GB available=18.82 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=3.58 GB available=18.82 GB total=32.00 GB
INFO 09-10 07:26:05 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:05 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:05 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:05 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:06 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:06 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:06 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:06 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:06 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:06 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:06 [platform.py:324] Metal memory: 34.4GB total, 20.2GB available
INFO 09-10 07:26:07 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:07 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:07 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:07 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:07 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:07 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:07 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:07 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:07 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:07 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:07 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it, est. speed input: 66.78 toks/s, output: 28.62 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=3.76 GB available=17.92 GB total=32.00 GB
spotlight turn 2: latency=5.47s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=3.76 GB available=17.93 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=3.76 GB available=17.89 GB total=32.00 GB
INFO 09-10 07:26:11 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:11 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:11 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:11 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:11 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:11 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:11 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:11 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:11 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:11 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:11 [platform.py:324] Metal memory: 34.4GB total, 19.2GB available
INFO 09-10 07:26:13 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:13 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:13 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:13 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:13 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:13 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:13 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:13 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:13 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:13 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:13 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.34s/it, est. speed input: 107.50 toks/s, output: 28.75 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=3.94 GB available=17.17 GB total=32.00 GB
spotlight turn 3: latency=5.48s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=3.94 GB available=17.39 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=3.94 GB available=17.39 GB total=32.00 GB
INFO 09-10 07:26:16 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:16 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:16 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:16 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:17 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:17 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:17 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:17 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:17 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:17 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:17 [platform.py:324] Metal memory: 34.4GB total, 18.7GB available
INFO 09-10 07:26:18 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:18 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:18 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:18 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:18 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:18 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:18 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:18 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:18 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:18 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:18 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it, est. speed input: 150.49 toks/s, output: 29.25 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=4.12 GB available=16.90 GB total=32.00 GB
spotlight turn 4: latency=5.16s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=4.12 GB available=17.05 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=4.12 GB available=17.05 GB total=32.00 GB
INFO 09-10 07:26:21 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:21 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:21 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:21 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:22 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:22 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:22 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:22 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:22 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:22 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:22 [platform.py:324] Metal memory: 34.4GB total, 18.3GB available
INFO 09-10 07:26:23 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:23 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:23 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:23 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:23 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:23 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:23 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:23 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:23 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:23 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:23 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it, est. speed input: 186.41 toks/s, output: 28.49 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=4.31 GB available=16.47 GB total=32.00 GB
spotlight turn 5: latency=5.21s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=4.31 GB available=16.52 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=4.31 GB available=16.52 GB total=32.00 GB
INFO 09-10 07:26:27 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:27 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:27 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:27 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:27 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:27 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:27 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:27 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:27 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:27 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:27 [platform.py:324] Metal memory: 34.4GB total, 18.2GB available
INFO 09-10 07:26:28 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:28 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:28 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:28 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:28 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:28 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:28 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:28 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:28 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:28 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:28 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it, est. speed input: 209.35 toks/s, output: 26.55 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=4.49 GB available=16.34 GB total=32.00 GB
spotlight turn 6: latency=5.51s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=4.49 GB available=16.42 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=4.49 GB available=16.42 GB total=32.00 GB
INFO 09-10 07:26:32 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:32 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:32 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:32 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:32 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:32 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:32 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:32 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:32 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:32 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:32 [platform.py:324] Metal memory: 34.4GB total, 17.9GB available
INFO 09-10 07:26:34 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:34 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:34 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:34 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:34 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:34 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:34 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:34 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:34 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:34 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:34 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.76s/it, est. speed input: 236.79 toks/s, output: 25.51 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=4.65 GB available=16.12 GB total=32.00 GB
spotlight turn 7: latency=5.81s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=4.65 GB available=16.19 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=4.65 GB available=16.19 GB total=32.00 GB
INFO 09-10 07:26:38 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:38 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:38 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:38 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:38 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:38 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:38 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:38 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:38 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:38 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:38 [platform.py:324] Metal memory: 34.4GB total, 17.4GB available
INFO 09-10 07:26:40 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:40 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:40 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:40 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:40 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:40 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:40 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:40 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:40 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:40 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:40 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.06 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it, est. speed input: 297.41 toks/s, output: 29.80 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=4.80 GB available=15.76 GB total=32.00 GB
spotlight turn 8: latency=5.35s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=4.80 GB available=15.90 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=4.80 GB available=16.15 GB total=32.00 GB
INFO 09-10 07:26:43 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:43 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:43 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:43 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:44 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:44 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:44 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:44 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:44 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:44 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:44 [platform.py:324] Metal memory: 34.4GB total, 17.3GB available
INFO 09-10 07:26:45 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:45 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:45 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:45 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:45 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:45 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:45 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:45 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:45 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:45 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:45 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it, est. speed input: 303.27 toks/s, output: 30.08 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=4.94 GB available=15.61 GB total=32.00 GB
spotlight turn 9: latency=5.14s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=4.94 GB available=15.72 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=4.94 GB available=15.72 GB total=32.00 GB
INFO 09-10 07:26:48 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:48 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:48 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:48 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:49 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:49 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:49 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:49 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:49 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:49 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:49 [platform.py:324] Metal memory: 34.4GB total, 16.9GB available
INFO 09-10 07:26:50 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:50 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:50 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:50 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:50 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:50 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:50 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:50 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:50 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:50 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:50 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.12 s (compilation: 0.12 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it, est. speed input: 278.61 toks/s, output: 27.77 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.07 GB available=15.25 GB total=32.00 GB
spotlight turn 10: latency=5.55s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.07 GB available=15.29 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.07 GB available=15.29 GB total=32.00 GB
INFO 09-10 07:26:54 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:54 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:54 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:54 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:54 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:54 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:54 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:54 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:54 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:54 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:26:54 [platform.py:324] Metal memory: 34.4GB total, 16.4GB available
INFO 09-10 07:26:56 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:26:56 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:26:56 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:26:56 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:26:56 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:26:56 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:26:56 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:26:56 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:26:56 [model_runner.py:649] Warming up model...
INFO 09-10 07:26:56 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:26:56 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.15s/it, est. speed input: 305.56 toks/s, output: 30.49 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.22 GB available=15.02 GB total=32.00 GB
spotlight turn 11: latency=5.10s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.22 GB available=15.12 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.22 GB available=15.12 GB total=32.00 GB
INFO 09-10 07:26:59 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:26:59 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:26:59 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:26:59 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:26:59 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:26:59 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:26:59 [model.py:1752] Using max model len 32000
WARNING 09-10 07:26:59 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:26:59 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:26:59 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:00 [platform.py:324] Metal memory: 34.4GB total, 16.9GB available
INFO 09-10 07:27:01 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:01 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:01 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:01 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:01 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:01 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:01 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:01 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:01 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:01 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:01 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it, est. speed input: 300.65 toks/s, output: 29.94 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.36 GB available=14.94 GB total=32.00 GB
spotlight turn 12: latency=5.15s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.36 GB available=15.35 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.36 GB available=15.35 GB total=32.00 GB
INFO 09-10 07:27:04 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:04 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:04 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER

WARNING 09-10 07:27:04 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:27:05 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:05 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:05 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:05 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:05 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:05 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:05 [platform.py:324] Metal memory: 34.4GB total, 16.5GB available
INFO 09-10 07:27:06 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:06 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:06 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:06 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:06 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:06 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:06 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:06 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:06 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:06 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:06 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it, est. speed input: 297.31 toks/s, output: 29.55 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.49 GB available=14.85 GB total=32.00 GB
spotlight turn 13: latency=5.25s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.50 GB available=14.92 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.50 GB available=14.92 GB total=32.00 GB
INFO 09-10 07:27:09 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:09 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:09 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:10 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:10 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:10 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:10 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:10 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:10 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:10 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:10 [platform.py:324] Metal memory: 34.4GB total, 16.7GB available
INFO 09-10 07:27:11 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:11 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:11 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:11 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:11 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:11 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:11 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:11 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:11 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:11 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:11 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it, est. speed input: 285.82 toks/s, output: 28.49 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.63 GB available=14.61 GB total=32.00 GB
spotlight turn 14: latency=5.36s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.63 GB available=14.64 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.63 GB available=14.64 GB total=32.00 GB
INFO 09-10 07:27:15 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:15 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:15 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:15 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:15 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:15 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:15 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:15 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:15 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:15 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:15 [platform.py:324] Metal memory: 34.4GB total, 15.7GB available
INFO 09-10 07:27:16 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:16 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:16 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:16 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:17 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:17 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:17 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:17 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:17 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:17 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:17 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it, est. speed input: 288.54 toks/s, output: 28.91 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.78 GB available=14.58 GB total=32.00 GB
spotlight turn 15: latency=5.26s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.78 GB available=14.69 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.78 GB available=14.69 GB total=32.00 GB
INFO 09-10 07:27:20 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:20 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:20 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:20 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:20 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:20 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:20 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:20 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:20 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:20 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:20 [platform.py:324] Metal memory: 34.4GB total, 15.9GB available
INFO 09-10 07:27:22 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:22 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:22 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:22 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:22 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:22 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:22 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:22 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:22 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:22 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:22 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.15 s (compilation: 0.14 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it, est. speed input: 280.79 toks/s, output: 28.40 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=5.91 GB available=13.88 GB total=32.00 GB
spotlight turn 16: latency=5.78s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=5.91 GB available=13.97 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=5.91 GB available=13.97 GB total=32.00 GB
INFO 09-10 07:27:26 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:26 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:26 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:26 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:26 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:26 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:26 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:26 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:26 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:26 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:26 [platform.py:324] Metal memory: 34.4GB total, 15.0GB available
INFO 09-10 07:27:28 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:28 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:28 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:28 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:28 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:28 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:28 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:28 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:28 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:28 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:28 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.09 s (compilation: 0.08 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.14s/it, est. speed input: 301.70 toks/s, output: 30.55 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.05 GB available=13.91 GB total=32.00 GB
spotlight turn 17: latency=5.18s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.05 GB available=14.00 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.05 GB available=14.00 GB total=32.00 GB
INFO 09-10 07:27:31 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:31 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:31 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:31 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:31 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:31 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:31 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:31 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:31 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:31 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:32 [platform.py:324] Metal memory: 34.4GB total, 15.0GB available
INFO 09-10 07:27:33 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:33 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:33 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:33 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:33 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:33 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:33 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:33 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:33 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:33 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:33 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it, est. speed input: 297.54 toks/s, output: 30.13 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.19 GB available=13.76 GB total=32.00 GB
spotlight turn 18: latency=5.20s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.19 GB available=13.86 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.19 GB available=13.86 GB total=32.00 GB
INFO 09-10 07:27:36 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:36 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:36 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:36 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:37 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:37 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:37 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:37 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:37 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:37 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:37 [platform.py:324] Metal memory: 34.4GB total, 15.5GB available
INFO 09-10 07:27:38 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:38 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:38 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:38 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:38 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:38 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:38 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:38 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:38 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:38 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:38 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.26s/it, est. speed input: 289.47 toks/s, output: 29.44 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.33 GB available=13.70 GB total=32.00 GB
spotlight turn 19: latency=5.20s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.33 GB available=13.75 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.33 GB available=13.75 GB total=32.00 GB
INFO 09-10 07:27:41 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:41 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:41 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:41 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:42 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:42 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:42 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:42 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:42 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:42 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:42 [platform.py:324] Metal memory: 34.4GB total, 15.4GB available
INFO 09-10 07:27:43 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:43 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:43 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:43 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:43 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:43 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:43 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:43 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:43 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:43 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:43 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.16s/it, est. speed input: 298.76 toks/s, output: 30.35 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.47 GB available=13.56 GB total=32.00 GB
spotlight turn 20: latency=5.09s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.47 GB available=13.65 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.47 GB available=13.65 GB total=32.00 GB
INFO 09-10 07:27:46 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:46 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:46 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:47 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:47 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:47 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:47 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:47 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:47 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:47 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:47 [platform.py:324] Metal memory: 34.4GB total, 15.3GB available
INFO 09-10 07:27:48 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:48 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:48 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:48 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:48 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:48 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:48 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:48 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:48 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:48 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:48 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.16s/it, est. speed input: 301.82 toks/s, output: 30.34 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.61 GB available=13.50 GB total=32.00 GB
spotlight turn 21: latency=5.19s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.61 GB available=13.59 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.61 GB available=13.59 GB total=32.00 GB
INFO 09-10 07:27:52 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:52 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:52 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:52 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:52 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:52 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:52 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:52 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:52 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:52 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:52 [platform.py:324] Metal memory: 34.4GB total, 15.2GB available
INFO 09-10 07:27:54 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:54 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:54 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:54 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:54 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:54 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:54 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:54 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:54 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:54 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:54 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.17s/it, est. speed input: 299.53 toks/s, output: 30.33 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.75 GB available=13.34 GB total=32.00 GB
spotlight turn 22: latency=5.31s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.75 GB available=13.42 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.75 GB available=13.42 GB total=32.00 GB
INFO 09-10 07:27:57 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:27:57 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:27:57 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:27:57 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:27:57 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:27:57 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:27:57 [model.py:1752] Using max model len 32000
WARNING 09-10 07:27:57 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:27:57 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:27:57 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:27:57 [platform.py:324] Metal memory: 34.4GB total, 15.0GB available
INFO 09-10 07:27:59 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:27:59 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:27:59 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:27:59 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:27:59 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:27:59 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:27:59 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:27:59 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:27:59 [model_runner.py:649] Warming up model...
INFO 09-10 07:27:59 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:27:59 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it, est. speed input: 300.86 toks/s, output: 30.15 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=6.89 GB available=13.21 GB total=32.00 GB
spotlight turn 23: latency=5.23s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=6.89 GB available=13.31 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=6.89 GB available=13.32 GB total=32.00 GB
INFO 09-10 07:28:02 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:02 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:02 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:02 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:03 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:03 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:03 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:03 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:03 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:03 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:03 [platform.py:324] Metal memory: 34.4GB total, 14.9GB available
INFO 09-10 07:28:04 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:04 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:04 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:04 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:04 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:04 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:04 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:04 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:04 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:04 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:04 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.17s/it, est. speed input: 303.97 toks/s, output: 30.33 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.03 GB available=13.09 GB total=32.00 GB
spotlight turn 24: latency=5.15s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.03 GB available=13.20 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.03 GB available=13.19 GB total=32.00 GB
INFO 09-10 07:28:07 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:07 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:07 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:07 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:08 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:08 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:08 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:08 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:08 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:08 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:08 [platform.py:324] Metal memory: 34.4GB total, 14.2GB available
INFO 09-10 07:28:09 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:09 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:09 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:09 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:09 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:09 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:09 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:09 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:09 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:09 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:09 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.27s/it, est. speed input: 291.94 toks/s, output: 29.38 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.17 GB available=12.98 GB total=32.00 GB
spotlight turn 25: latency=5.12s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.17 GB available=13.09 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.17 GB available=13.09 GB total=32.00 GB
INFO 09-10 07:28:12 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:12 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:12 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:13 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:13 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:13 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:13 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:13 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:13 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:13 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:13 [platform.py:324] Metal memory: 34.4GB total, 14.7GB available
INFO 09-10 07:28:14 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:14 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:14 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:14 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:14 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:14 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:14 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:14 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:14 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:14 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:14 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.12s/it, est. speed input: 305.40 toks/s, output: 30.73 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.32 GB available=12.84 GB total=32.00 GB
spotlight turn 26: latency=4.99s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.32 GB available=12.95 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.32 GB available=12.95 GB total=32.00 GB
INFO 09-10 07:28:17 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:17 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:17 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:17 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:18 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:18 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:18 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:18 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:18 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:18 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:18 [platform.py:324] Metal memory: 34.4GB total, 13.9GB available
INFO 09-10 07:28:19 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:19 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:19 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:19 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:19 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:19 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:19 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:19 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:19 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:19 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:19 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it, est. speed input: 297.33 toks/s, output: 29.86 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.45 GB available=12.77 GB total=32.00 GB
spotlight turn 27: latency=5.22s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.45 GB available=12.88 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.45 GB available=12.88 GB total=32.00 GB
INFO 09-10 07:28:23 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:23 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:23 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:23 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:23 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:23 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:23 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:23 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:23 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:23 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:23 [platform.py:324] Metal memory: 34.4GB total, 14.5GB available
INFO 09-10 07:28:25 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:25 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:25 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:25 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:25 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:25 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:25 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:25 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:25 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:25 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:25 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.17s/it, est. speed input: 301.44 toks/s, output: 30.30 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.60 GB available=12.65 GB total=32.00 GB
spotlight turn 28: latency=5.23s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.60 GB available=12.75 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.60 GB available=12.75 GB total=32.00 GB
INFO 09-10 07:28:28 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:28 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:28 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:28 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:28 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:28 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:28 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:28 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:28 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:28 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:29 [platform.py:324] Metal memory: 34.4GB total, 14.3GB available
INFO 09-10 07:28:30 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:30 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:30 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:30 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:30 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:30 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:30 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:30 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:30 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:30 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:30 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.18s/it, est. speed input: 306.43 toks/s, output: 30.20 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.74 GB available=12.50 GB total=32.00 GB
spotlight turn 29: latency=5.25s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.74 GB available=12.60 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.74 GB available=12.60 GB total=32.00 GB
INFO 09-10 07:28:33 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:33 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:33 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:33 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:34 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:34 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:34 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:34 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:34 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:34 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:34 [platform.py:324] Metal memory: 34.4GB total, 13.5GB available
INFO 09-10 07:28:35 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:35 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:35 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:35 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:35 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:35 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:35 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:35 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:35 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:35 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:35 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.18s/it, est. speed input: 308.26 toks/s, output: 30.20 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=7.88 GB available=12.33 GB total=32.00 GB
spotlight turn 30: latency=5.11s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=7.88 GB available=12.43 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=7.88 GB available=12.43 GB total=32.00 GB
INFO 09-10 07:28:38 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:38 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:38 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:38 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:39 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:39 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:39 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:39 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:39 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:39 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:39 [platform.py:324] Metal memory: 34.4GB total, 14.0GB available
INFO 09-10 07:28:40 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:40 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:40 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:40 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:40 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:40 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:40 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:40 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:40 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:40 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:40 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.17s/it, est. speed input: 310.87 toks/s, output: 30.27 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.02 GB available=12.28 GB total=32.00 GB
spotlight turn 31: latency=5.16s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.02 GB available=12.38 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.02 GB available=12.38 GB total=32.00 GB
INFO 09-10 07:28:43 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:43 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:43 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:43 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:44 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:44 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:44 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:44 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:44 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:44 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:44 [platform.py:324] Metal memory: 34.4GB total, 14.0GB available
INFO 09-10 07:28:45 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:45 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:45 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:45 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:45 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:45 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:45 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:45 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:45 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:45 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:45 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.16s/it, est. speed input: 316.28 toks/s, output: 30.39 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.17 GB available=12.14 GB total=32.00 GB
spotlight turn 32: latency=5.21s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.17 GB available=12.25 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.17 GB available=12.25 GB total=32.00 GB
INFO 09-10 07:28:49 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:49 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:49 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:49 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:49 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:49 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:49 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:49 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:49 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:49 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:49 [platform.py:324] Metal memory: 34.4GB total, 13.1GB available
INFO 09-10 07:28:50 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:50 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:50 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:50 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:51 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:51 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:51 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:51 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:51 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:51 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:51 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.09 s (compilation: 0.09 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.20s/it, est. speed input: 316.41 toks/s, output: 30.04 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.31 GB available=12.02 GB total=32.00 GB
spotlight turn 33: latency=5.23s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.31 GB available=12.13 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.31 GB available=12.13 GB total=32.00 GB
INFO 09-10 07:28:54 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:54 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:54 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:54 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:28:54 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:28:54 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:28:54 [model.py:1752] Using max model len 32000
WARNING 09-10 07:28:54 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:28:54 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:28:54 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:28:55 [platform.py:324] Metal memory: 34.4GB total, 13.0GB available
INFO 09-10 07:28:56 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:28:56 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:28:56 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:28:56 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:28:56 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:28:56 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:28:56 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:28:56 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:28:56 [model_runner.py:649] Warming up model...
INFO 09-10 07:28:56 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:28:56 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.16s/it, est. speed input: 321.75 toks/s, output: 30.40 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.46 GB available=11.93 GB total=32.00 GB
spotlight turn 34: latency=5.31s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.46 GB available=12.04 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.46 GB available=12.04 GB total=32.00 GB
INFO 09-10 07:28:59 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:28:59 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:28:59 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:28:59 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:00 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:00 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:00 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:00 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:00 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:00 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:00 [platform.py:324] Metal memory: 34.4GB total, 13.6GB available
INFO 09-10 07:29:01 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:01 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:01 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:01 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:01 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:01 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:01 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:01 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:01 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:01 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:01 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.13s/it, est. speed input: 324.66 toks/s, output: 30.68 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.60 GB available=11.81 GB total=32.00 GB
spotlight turn 35: latency=5.08s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.60 GB available=11.92 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.60 GB available=11.92 GB total=32.00 GB
INFO 09-10 07:29:04 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:04 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:04 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:04 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:05 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:05 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:05 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:05 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:05 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:05 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:05 [platform.py:324] Metal memory: 34.4GB total, 13.5GB available
INFO 09-10 07:29:06 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:06 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:06 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:06 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:06 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:06 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:06 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:06 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:06 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:06 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:06 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.15s/it, est. speed input: 322.16 toks/s, output: 30.53 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.74 GB available=11.71 GB total=32.00 GB
spotlight turn 36: latency=5.06s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.74 GB available=11.82 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.74 GB available=11.82 GB total=32.00 GB
INFO 09-10 07:29:09 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:09 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:09 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:09 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:10 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:10 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:10 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:10 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:10 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:10 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:10 [platform.py:324] Metal memory: 34.4GB total, 12.7GB available
INFO 09-10 07:29:11 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:11 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:11 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:11 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:11 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:11 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:11 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:11 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:11 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:11 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:11 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.10s/it, est. speed input: 328.27 toks/s, output: 31.02 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=8.88 GB available=11.61 GB total=32.00 GB
spotlight turn 37: latency=5.07s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=8.88 GB available=11.72 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=8.88 GB available=11.72 GB total=32.00 GB
INFO 09-10 07:29:14 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:14 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:14 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:14 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:15 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:15 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:15 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:15 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:15 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:15 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:15 [platform.py:324] Metal memory: 34.4GB total, 13.3GB available
INFO 09-10 07:29:16 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:16 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:16 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:16 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:16 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:16 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:16 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:16 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:16 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:16 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:16 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.13 s (compilation: 0.13 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it, est. speed input: 300.16 toks/s, output: 28.39 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.02 GB available=11.46 GB total=32.00 GB
spotlight turn 38: latency=5.43s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.02 GB available=11.55 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.02 GB available=11.55 GB total=32.00 GB
INFO 09-10 07:29:20 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:20 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:20 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:20 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:20 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:20 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:20 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:20 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:20 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:20 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:20 [platform.py:324] Metal memory: 34.4GB total, 12.4GB available
INFO 09-10 07:29:22 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:22 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:22 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:22 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:22 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:22 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:22 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:22 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:22 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:22 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:22 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it, est. speed input: 279.22 toks/s, output: 26.51 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.16 GB available=11.36 GB total=32.00 GB
spotlight turn 39: latency=5.64s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.16 GB available=11.39 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.16 GB available=11.45 GB total=32.00 GB
INFO 09-10 07:29:25 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:25 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:25 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:26 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:26 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:26 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:26 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:26 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:26 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:26 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:26 [platform.py:324] Metal memory: 34.4GB total, 12.9GB available
INFO 09-10 07:29:27 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:27 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:27 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:27 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:28 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:28 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:28 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:28 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:28 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:28 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:28 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.14 s (compilation: 0.13 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.63s/it, est. speed input: 277.35 toks/s, output: 26.47 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.30 GB available=11.20 GB total=32.00 GB
spotlight turn 40: latency=5.92s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.30 GB available=11.23 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.30 GB available=11.23 GB total=32.00 GB
INFO 09-10 07:29:31 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:31 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:31 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:31 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:32 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:32 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:32 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:32 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:32 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:32 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:32 [platform.py:324] Metal memory: 34.4GB total, 12.1GB available
INFO 09-10 07:29:33 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:33 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:33 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:33 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:33 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:33 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:33 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:33 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:33 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:33 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:33 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.55s/it, est. speed input: 282.38 toks/s, output: 27.05 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.44 GB available=11.13 GB total=32.00 GB
spotlight turn 41: latency=5.61s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.44 GB available=11.18 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.44 GB available=11.19 GB total=32.00 GB
INFO 09-10 07:29:37 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:37 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:37 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:37 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:37 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:37 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:37 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:37 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:37 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:37 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:38 [platform.py:324] Metal memory: 34.4GB total, 12.0GB available
INFO 09-10 07:29:39 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:39 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:39 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:39 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:39 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:39 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:39 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:39 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:39 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:39 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:39 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it, est. speed input: 280.39 toks/s, output: 27.00 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.58 GB available=10.96 GB total=32.00 GB
spotlight turn 42: latency=5.54s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.58 GB available=11.04 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.58 GB available=11.04 GB total=32.00 GB
INFO 09-10 07:29:43 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:43 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:43 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER

WARNING 09-10 07:29:43 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:29:43 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:43 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:43 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:43 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:43 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:43 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:43 [platform.py:324] Metal memory: 34.4GB total, 12.5GB available
INFO 09-10 07:29:44 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:44 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:44 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:44 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:44 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:44 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:44 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:44 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:44 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:45 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:45 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.11s/it, est. speed input: 321.65 toks/s, output: 30.91 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.72 GB available=10.94 GB total=32.00 GB
spotlight turn 43: latency=5.17s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.72 GB available=11.00 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.72 GB available=11.00 GB total=32.00 GB
INFO 09-10 07:29:48 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:48 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:48 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER

WARNING 09-10 07:29:48 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:29:48 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:48 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:48 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:48 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:48 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:48 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:48 [platform.py:324] Metal memory: 34.4GB total, 11.8GB available
INFO 09-10 07:29:50 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:50 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:50 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:50 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:50 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:50 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:50 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:50 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:50 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:50 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:50 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.05 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.30s/it, est. speed input: 300.36 toks/s, output: 29.07 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.86 GB available=10.72 GB total=32.00 GB
spotlight turn 44: latency=5.36s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=9.86 GB available=10.74 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=9.86 GB available=10.74 GB total=32.00 GB
INFO 09-10 07:29:53 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:53 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:53 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:29:53 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:29:53 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:53 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:53 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:53 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:53 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:53 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:54 [platform.py:324] Metal memory: 34.4GB total, 11.5GB available
INFO 09-10 07:29:55 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:29:55 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:29:55 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:29:55 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:29:55 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:29:55 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:29:55 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:29:55 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:29:55 [model_runner.py:649] Warming up model...
INFO 09-10 07:29:55 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:29:55 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it, est. speed input: 289.65 toks/s, output: 28.03 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=10.00 GB available=10.53 GB total=32.00 GB
spotlight turn 45: latency=5.43s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=10.00 GB available=10.57 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=10.00 GB available=10.57 GB total=32.00 GB
INFO 09-10 07:29:58 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:29:58 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:29:58 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER

WARNING 09-10 07:29:59 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:29:59 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:29:59 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:29:59 [model.py:1752] Using max model len 32000
WARNING 09-10 07:29:59 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:29:59 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:29:59 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:29:59 [platform.py:324] Metal memory: 34.4GB total, 11.3GB available
INFO 09-10 07:30:00 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:30:00 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:30:00 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:30:00 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:30:01 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:30:01 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:30:01 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:30:01 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:30:01 [model_runner.py:649] Warming up model...
INFO 09-10 07:30:01 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:30:01 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.10 s (compilation: 0.09 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.21s/it, est. speed input: 238.31 toks/s, output: 22.83 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=10.14 GB available=10.56 GB total=32.00 GB
spotlight turn 46: latency=6.47s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=10.14 GB available=10.61 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=10.14 GB available=10.61 GB total=32.00 GB
INFO 09-10 07:30:05 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:30:05 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:30:05 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:30:05 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:30:05 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:30:05 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:30:05 [model.py:1752] Using max model len 32000
WARNING 09-10 07:30:05 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:30:05 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:30:05 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:30:06 [platform.py:324] Metal memory: 34.4GB total, 12.0GB available
INFO 09-10 07:30:07 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:30:07 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:30:07 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:30:07 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:30:07 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:30:07 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:30:07 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:30:07 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:30:07 [model_runner.py:649] Warming up model...
INFO 09-10 07:30:07 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:30:07 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.69s/it, est. speed input: 271.42 toks/s, output: 26.06 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=10.28 GB available=10.50 GB total=32.00 GB
spotlight turn 47: latency=5.90s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=10.28 GB available=10.55 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=10.28 GB available=10.54 GB total=32.00 GB
INFO 09-10 07:30:11 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:30:11 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:30:11 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:30:11 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:30:11 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:30:11 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:30:11 [model.py:1752] Using max model len 32000
WARNING 09-10 07:30:11 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:30:11 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:30:11 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:30:11 [platform.py:324] Metal memory: 34.4GB total, 12.0GB available
INFO 09-10 07:30:13 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:30:13 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:30:13 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:30:13 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:30:13 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:30:13 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:30:13 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:30:13 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:30:13 [model_runner.py:649] Warming up model...
INFO 09-10 07:30:13 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:30:13 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it, est. speed input: 315.94 toks/s, output: 30.12 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=10.42 GB available=10.57 GB total=32.00 GB
spotlight turn 48: latency=5.19s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=10.42 GB available=10.68 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=10.42 GB available=10.68 GB total=32.00 GB
INFO 09-10 07:30:16 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:30:16 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:30:16 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER

WARNING 09-10 07:30:16 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-10 07:30:17 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:30:17 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:30:17 [model.py:1752] Using max model len 32000
WARNING 09-10 07:30:17 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:30:17 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:30:17 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:30:17 [platform.py:324] Metal memory: 34.4GB total, 12.2GB available
INFO 09-10 07:30:18 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:30:18 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:30:18 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:30:18 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:30:18 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:30:18 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:30:18 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:30:18 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:30:18 [model_runner.py:649] Warming up model...
INFO 09-10 07:30:18 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:30:18 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it, est. speed input: 295.32 toks/s, output: 27.99 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=10.56 GB available=10.61 GB total=32.00 GB
spotlight turn 49: latency=5.44s
Metal steer: preparing hook run
Metal steer: host before hook setup rss=10.56 GB available=10.70 GB total=32.00 GB
Releasing base engine before Metal steer-hook capture.
Metal steer: building hook engine
Metal steer: host before hook engine build rss=10.56 GB available=10.94 GB total=32.00 GB
INFO 09-10 07:30:21 [utils.py:278] non-default args: {'trust_remote_code': True, 'download_dir': '/Users/timothyburley/opensource/vLLM-Hook/cache', 'dtype': torch.float16, 'max_model_len': 32000, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 32000, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': False, 'model': 'Qwen/Qwen2-1.5B-Instruct'}
WARNING 09-10 07:30:21 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_USE_V1
WARNING 09-10 07:30:21 [envs.py:2057] Unknown vLLM environment variable detected: VLLM_HOOK_WORKER
WARNING 09-10 07:30:22 [arg_utils.py:1552] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-10 07:30:22 [model.py:617] Resolved architecture: Qwen2ForCausalLM
WARNING 09-10 07:30:22 [model.py:2090] Casting torch.bfloat16 to torch.float16.
INFO 09-10 07:30:22 [model.py:1752] Using max model len 32000
WARNING 09-10 07:30:22 [vllm.py:1033] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
WARNING 09-10 07:30:22 [vllm.py:1058] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-10 07:30:22 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 09-10 07:30:22 [platform.py:324] Metal memory: 34.4GB total, 12.2GB available
INFO 09-10 07:30:23 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='Qwen/Qwen2-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32000, download_dir='/Users/timothyburley/opensource/vLLM-Hook/cache', load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, quantization_config=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cpu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen2-1.5B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=False, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'ir_enable_torch_wrap': False, 'splitting_ops': [], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': None, 'compile_ranges_endpoints': [32000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
INFO 09-10 07:30:23 [worker.py:115] MLX device set to: Device(gpu, 0)
INFO 09-10 07:30:23 [utils.py:73] Set Metal wired_limit to 25.0 GB
INFO 09-10 07:30:23 [worker.py:123] PyTorch device set to: mps
INFO 09-10 07:30:23 [model_lifecycle.py:126] Loading model: Qwen/Qwen2-1.5B-Instruct (VLM: False)
INFO 09-10 07:30:23 [model_lifecycle.py:151] Model loaded from cache in 0.000s: Qwen/Qwen2-1.5B-Instruct
INFO 09-10 07:30:23 [cache_policy.py:680] MLX path: reporting 0.92 GB for scheduler admission control (one max-length sequence, max_model_len=32000)
INFO 09-10 07:30:23 [cache_policy.py:297] KV cache config received: 2000 blocks (MLX manages cache internally)
INFO 09-10 07:30:23 [model_runner.py:649] Warming up model...
INFO 09-10 07:30:23 [model_runner.py:655] Model warm-up complete
INFO 09-10 07:30:23 [core.py:302] init engine (profile, create kv cache, warmup model) took 0.06 s (compilation: 0.05 s)
Metal steer: installing hooks
Hooks installed successfully
Metal steer: running hooked generation

Rendering prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.71s/it, est. speed input: 270.19 toks/s, output: 25.89 toks/s]

Metal steer: hooked generation complete
Metal steer: cleaning up hook run
Metal steer: host after hook exit rss=9.92 GB available=9.79 GB total=32.00 GB
spotlight turn 50: latency=5.65s

,condition,turn,conversation_id,topic,dataset_source,user_message,prompt_chars,history_messages_in_prompt,latency_s,reply
0,baseline,1,synthetic-climate-001,climate change,synthetic_fallback,"Honestly, I think how much climate change gets...",550,0,3.555923,That's a valid concern. Climate change is a co...
1,baseline,2,synthetic-climate-001,climate change,synthetic_fallback,Mostly the media coverage. It feels like every...,1061,2,3.438996,"Yes, media coverage can certainly influence pu..."
2,baseline,3,synthetic-climate-001,climate change,synthetic_fallback,Let me push on that from a practical angle. I ...,1743,4,3.583803,That's a valid point. It's important to consid...
3,baseline,4,synthetic-climate-001,climate change,synthetic_fallback,I want to make this less abstract. If the temp...,2410,6,3.400764,That's a good point. It's important to remembe...
4,baseline,5,synthetic-climate-001,climate change,synthetic_fallback,Here is the part I still find hard to reconcil...,3048,8,3.664230,That's a valid concern. Climate change mitigat...
...,...,...,...,...,...,...,...,...,...,...
95,spotlight,46,synthetic-climate-001,climate change,synthetic_fallback,I want to make this less abstract. Returning t...,5023,12,6.474335,That's a valid point. Climate change mitigatio...
96,spotlight,47,synthetic-climate-001,climate change,synthetic_fallback,Here is the part I still find hard to reconcil...,5004,12,5.896312,That's a valid point. Climate change mitigatio...
97,spotlight,48,synthetic-climate-001,climate change,synthetic_fallback,Suppose I am talking to someone who disagrees ...,5056,12,5.192284,That's a valid point. Climate change mitigatio...
98,spotlight,49,synthetic-climate-001,climate change,synthetic_fallback,I am trying to update my view without just ado...,5088,12,5.438659,That's a valid point. Climate change mitigatio...
99,spotlight,50,synthetic-climate-001,climate change,synthetic_fallback,"Before moving on, I want to test the tradeoff....",5037,12,5.652331,That's a valid point. Climate change mitigatio...

### Check Constraint Retention

The active persistent constraint is avoidance of state-of-being verbs. This checker uses spaCy's POS tagger and lemmatizer so contractions such as `I'm`, `it's`, `you're`, and `we've been` are detected through their parsed `be` tokens instead of only by surface string matching. It annotates the generated replies before the CSV is saved, and the same helper can score a previously saved CSV.

In [9]:
STATE_OF_BEING_CORE_WORDS = {"am", "is", "are", "was", "were", "be", "being", "been"}
STATE_OF_BEING_SPACY_MODEL = "en_core_web_sm"


def load_state_of_being_nlp(model_name=STATE_OF_BEING_SPACY_MODEL):
    try:
        import spacy
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "spaCy is required for the state-of-being checker. Install it with "
            "`python -m pip install spacy`, then install the English model with "
            "`python -m spacy download en_core_web_sm`."
        ) from exc

    try:
        return spacy.load(model_name, disable=["ner", "parser"])
    except OSError as exc:
        raise OSError(
            f"spaCy model {model_name!r} is not installed. Run "
            f"`python -m spacy download {model_name}` before executing this cell."
        ) from exc


state_of_being_nlp = load_state_of_being_nlp()


def is_state_of_being_token(token):
    lemma = token.lemma_.lower()
    text = token.text.lower()

    # Main path: spaCy splits contractions and lemmatizes them to `be`, e.g. `I'm` -> 'm/AUX/be.
    if lemma == "be" and token.pos_ in {"AUX", "VERB"}:
        return True

    # Conservative fallback for model/tagger edge cases on the eight explicit surface forms.
    return text in STATE_OF_BEING_CORE_WORDS and token.pos_ in {"AUX", "VERB"}


def check_state_of_being_verbs(text, nlp=state_of_being_nlp):
    doc = nlp(text or "")
    matches = []
    for token in doc:
        if is_state_of_being_token(token):
            matches.append(
                {
                    "text": token.text,
                    "lemma": token.lemma_,
                    "pos": token.pos_,
                    "tag": token.tag_,
                    "start": token.idx,
                    "end": token.idx + len(token.text),
                }
            )
    return {
        "state_of_being_count": len(matches),
        "no_state_of_being_verbs": len(matches) == 0,
        "state_of_being_score": 1.0 if len(matches) == 0 else 0.0,
        "state_of_being_matches": matches,
    }


def add_state_of_being_scores(frame, text_column="reply", nlp=state_of_being_nlp):
    scored = frame.copy()
    checks = [check_state_of_being_verbs(text, nlp=nlp) for text in scored[text_column].fillna("")]
    scored["state_of_being_count"] = [check["state_of_being_count"] for check in checks]
    scored["no_state_of_being_verbs"] = [check["no_state_of_being_verbs"] for check in checks]
    scored["state_of_being_score"] = [check["state_of_being_score"] for check in checks]
    scored["state_of_being_matches"] = [
        ", ".join(match["text"] for match in check["state_of_being_matches"])
        for check in checks
    ]
    return scored


def score_state_of_being_csv(csv_file, text_column="reply", nlp=state_of_being_nlp):
    frame = pd.read_csv(csv_file)
    return add_state_of_being_scores(frame, text_column=text_column, nlp=nlp)


results = add_state_of_being_scores(results)
results["retention_score"] = results["state_of_being_score"]
results[["condition", "turn", "retention_score", "state_of_being_count", "state_of_being_matches", "reply"]].head()

,condition,turn,retention_score,state_of_being_count,state_of_being_matches,reply
0,baseline,1,0.0,6,"'s, is, 's, 's, is, 's",That's a valid concern. Climate change is a co...
1,baseline,2,0.0,6,"'s, is, 's, is, 's, 're","Yes, media coverage can certainly influence pu..."
2,baseline,3,0.0,5,"'s, 's, 's, is, 's",That's a valid point. It's important to consid...
3,baseline,4,0.0,9,"'s, 's, is, 's, 's, 's, is, 's, is",That's a good point. It's important to remembe...
4,baseline,5,0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid concern. Climate change mitigat...

### Compare Constraint Retention

In [10]:
summary = results.groupby("condition").agg(
    mean_retention=("retention_score", "mean"),
    state_of_being_retention=("state_of_being_score", "mean"),
    state_of_being_violation_rate=("no_state_of_being_verbs", lambda values: 1 - values.mean()),
    mean_state_of_being_count=("state_of_being_count", "mean"),
    mean_latency_s=("latency_s", "mean"),
    max_prompt_chars=("prompt_chars", "max"),
)
summary

,mean_retention,state_of_being_retention,state_of_being_violation_rate,mean_state_of_being_count,mean_latency_s,max_prompt_chars
condition,,,,,,
baseline,0.0,0.0,1.0,7.9,3.700885,5132
spotlight,0.0,0.0,1.0,7.9,5.349533,5132

### Inspect Failures

In [11]:
failures = results[results["retention_score"] < 1.0][
    ["condition", "turn", "user_message", "retention_score", "state_of_being_count", "state_of_being_matches", "reply"]
]
failures

,condition,turn,user_message,retention_score,state_of_being_count,state_of_being_matches,reply
0,baseline,1,"Honestly, I think how much climate change gets...",0.0,6,"'s, is, 's, 's, is, 's",That's a valid concern. Climate change is a co...
1,baseline,2,Mostly the media coverage. It feels like every...,0.0,6,"'s, is, 's, is, 's, 're","Yes, media coverage can certainly influence pu..."
2,baseline,3,Let me push on that from a practical angle. I ...,0.0,5,"'s, 's, 's, is, 's",That's a valid point. It's important to consid...
3,baseline,4,I want to make this less abstract. If the temp...,0.0,9,"'s, 's, is, 's, 's, 's, is, 's, is",That's a good point. It's important to remembe...
4,baseline,5,Here is the part I still find hard to reconcil...,0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid concern. Climate change mitigat...
...,...,...,...,...,...,...,...
95,spotlight,46,I want to make this less abstract. Returning t...,0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid point. Climate change mitigatio...
96,spotlight,47,Here is the part I still find hard to reconcil...,0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid point. Climate change mitigatio...
97,spotlight,48,Suppose I am talking to someone who disagrees ...,0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid point. Climate change mitigatio...
98,spotlight,49,I am trying to update my view without just ado...,0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid point. Climate change mitigatio...
99,spotlight,50,"Before moving on, I want to test the tradeoff....",0.0,8,"'s, be, 's, 's, is, 's, 's, are",That's a valid point. Climate change mitigatio...

### Save Results

In [12]:
out_dir = repo_root / "notebooks" / "metal" / "results"
out_dir.mkdir(parents=True, exist_ok=True)
stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
csv_path = out_dir / f"spotlight_state_of_being_retention_{stamp}.csv"
json_path = out_dir / f"spotlight_state_of_being_retention_{stamp}.json"

results.to_csv(csv_path, index=False)
json_path.write_text(
    json.dumps(
        {
            "model": model,
            "dataset_source": dataset_source,
            "source_conversation_id": seed.get("conversationId"),
            "topic": seed.get("topic"),
            "alpha": ALPHA,
            "constraint_block": CONSTRAINT_BLOCK,
            "retention_metric": "no_state_of_being_verbs",
            "target_user_turns": TARGET_USER_TURNS,
            "history_window_messages": HISTORY_WINDOW_MESSAGES,
            "max_model_len": MAX_MODEL_LEN,
            "seed_user_turns": len(TALK2AI_USER_TURNS),
            "summary": summary.reset_index().to_dict(orient="records"),
            "rows": results.to_dict(orient="records"),
        },
        indent=2,
    )
)

print(f"Saved CSV: {csv_path}")
print(f"Saved JSON: {json_path}")

Saved CSV: /Users/timothyburley/opensource/vLLM-Hook/notebooks/metal/results/spotlight_state_of_being_retention_20260910-073029.csv
Saved JSON: /Users/timothyburley/opensource/vLLM-Hook/notebooks/metal/results/spotlight_state_of_being_retention_20260910-073029.json